### ISSUE TITLE
Roller 5d100 does not work

### ISSUE THREAD

**Issue by tsalmela** [villheik/Rankaisijabot#6]
Hello. 

Tried this awesome bot and noticed that **!roll 5d100** does not work even though the bot specifically even gives it as an example command. 

"Syötä komento muodossa NdN+N tai NdN (eli vaikka 1d20+3 tai 5d100)"

**Comment by tsalmela** [comment]
It was a dice :D please add alias roll since it is a lot more intuitive. :)

**Comment by villheik** [comment]
!roll already exists and it rolls a number between 1 and n (default 100)
